using System.Numerics;
using Microsoft.VisualBasic;
using BigLion.Application.Common.Interfaces;
using BigLion.Domain.Entities;

namespace BigLion.Application.Features.Systems.Commands;
public class RecommendationDataInitializerCommand : IRequest<Unit> { }
public class RecommendationDataInitializerCommandHandler : IRequestHandler<RecommendationDataInitializerCommand, Unit>
{
    private readonly ICheckupDatabaseContext _context;

    public RecommendationDataInitializerCommandHandler(ICheckupDatabaseContext checkupDatabaseContext)
    {
        _context = checkupDatabaseContext;
    }

    public async Task<Unit> Handle(RecommendationDataInitializerCommand request, CancellationToken cancellationToken)
    {
        await SeedRecommendations(cancellationToken); 
        return Unit.Value;
    }

    private async Task SeedRecommendations(CancellationToken cancellationToken)
    {
        if (await _context.Recommendations.AnyAsync(cancellationToken))
        {
            return;
        }

        var Recommendation = new[]
        {
            new Recommendation("BMI","BMI L","B","","",0,18.5,"ดัชนีมวลกาย (BMI) : น้ำหนักน้อยกว่าเกณฑ์มาตรฐาน","","แนะนำรับประทานอาหารที่มีประโยชน์ต่อร่างกาย  เน้นอาหารจำพวกคาร์โบไฮเดตรและโปรตีนที่ได้จากเนื้อสัตว์  ออกกำลังกายสม่ำเสมอ  พักผ่อนให้เพียงพอ","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("BMI","BMI Normal","B","","",18.5,22.99,"ดัชนีมวลกาย (BMI) : สมส่วน","- Body Mass Index : Normal","แนะนำรับประทานอาหารให้ครบห้าหมู่  ออกกำลังการสม่ำเสมออย่างน้อย 3 วันต่อสัปดาห์ ต่อเนื่องอย่างน้อย 30 นาทีต่อครั้ง พักผ่อนให้เพียงพอ","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("BMI","BMI H","B","","",23,24.99,"ดัชนีมวลกาย (BMI) : ท้วม","","แนะนำรับประทานอาหารให้ครบห้าหมู่  ลดอาหารจำพวกไขมันที่ได้จากสัตว์  อาหาร ผลไม้ที่มีรสหวาน  ออกกำลังการสม่ำเสมออย่างน้อย 3 วันต่อสัปดาห์ ต่อเนื่องอย่างน้อย 30 นาทีต่อครั้ง","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("BMI","BMI HH","B","","",25,9999,"ดัชนีมวลกาย (BMI) : น้ำหนักเกินเกณฑ์มาตรฐาน","","แนะนำรับประทานอาหารให้ครบห้าหมู่  ลดอาหารจำพวกไขมันที่ได้จากสัตว์  อาหาร ผลไม้ที่มีรสหวาน  ออกกำลังการสม่ำเสมออย่างน้อย 3 วันต่อสัปดาห์ ต่อเนื่องอย่างน้อย 30 นาทีต่อครั้ง แนะนำพบแพทย์ปรึกษาเรื่องโภชนาการและการควบคุมอาหารและน้ำหนัก  เพื่อลดภาวะเสี่ยงในการเกิดโรคต่างๆ","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("BP","Diastolic BP L","B","","",0,59,"ความดันโลหิตต่ำ","","หมั่นติดตามวัดความดันโลหิต  พักผ่อนให้เพียงพอ  ออกกำลังกายสม่ำเสมอ หลีกเลี่ยงการเปลี่ยนอริยาบทอย่างรวดเร็วเกินไป เพราะอาจทำให้เกิดอาการหน้ามืดวิงเวียนได้","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("BP","Systolic BP H","B","","",130,139,"ความดันโลหิตสูง","","ควรหลีกเลี่ยง : อาหารแปรรูป อาหารหมักดอง อาหารที่มีรสชาติเค็มจัด เช่น ไส้กรอก ปลาร้า หมูยอ ปลากระป๋อง หลีกเลี่ยงการสูบบุหรี่และแอลกอฮอลล์  ควรรับประทานอาหารให้ครบ 5 หมู่ และออกกำลังกายเป็นประจำ","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HEMO","Hb L ญ","B","F","",0,11.99,"ความเข้มข้นของเลือดต่ำกว่าเกณฑ์ปกติ","Complete blood count : Little pale. May lack iron. Eat liver,green-leave vegetable and milk recommended","ควรรับประทาน : อาหารที่มีธาตุเหล็กสูง เช่น ผักใบเขียว อาหารประเภทเครื่องในสัตว์ เช่น  เลือดไก่/หมู ตับ  กินผลไม้ที่มีวิตามินซีสูงพร้อมมื้ออาหาร เพื่อเพิ่มการดูดซึมธาตุเหล็ก (แนะนำหลีกเลี่ยงการดื่มนมพร้อมมื้ออาหาร)","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HEMO","Hb NORMAL ญ","B","F","",12,16,"ความเข้มข้นของเลือดอยู่ในเกณฑ์ปกติ","Complete blood count : Normal","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HEMO","Hb H ญ","B","F","",16.01,9999,"ความเข้มข้นของเลือดสูงกว่าเกณฑ์ปกติ","","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HEMO","Hb L ช","B","M","",0,12.99,"ความเข้มข้นของเลือดต่ำกว่าเกณฑ์ปกติ","","ควรรับประทาน : อาหารที่มีธาตุเหล็กสูง เช่น ผักใบเขียว อาหารประเภทเครื่องในสัตว์ เช่น  เลือดไก่/หมู ตับ  กินผลไม้ที่มีวิตามินซีสูงพร้อมมื้ออาหาร เพื่อเพิ่มการดูดซึมธาตุเหล็ก (แนะนำหลีกเลี่ยงการดื่มนมพร้อมมื้ออาหาร)","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HEMO","Hb Normal ช","B","M","",13,18,"ความเข้มข้นของเลือดอยู่ในเกณฑ์ปกติ","","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HEMO","Hb H ช","B","M","",18.01,9999,"ความเข้มข้นของเลือดสูงกว่าเกณฑ์ปกติ","","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HCT","Hct L ญ","B","F","",0,35.99,"ความเข้มข้นของเลือดต่ำกว่าเกณฑ์ปกติ","Complete blood count : Little pale. May lack iron. Eat liver,green-leave vegetable and milk recommended","ควรรับประทาน : อาหารที่มีธาตุเหล็กสูง เช่น ผักใบเขียว อาหารประเภทเครื่องในสัตว์ เช่น  เลือดไก่/หมู ตับ  กินผลไม้ที่มีวิตามินซีสูงพร้อมมื้ออาหาร เพื่อเพิ่มการดูดซึมธาตุเหล็ก (แนะนำหลีกเลี่ยงการดื่มนมพร้อมมื้ออาหาร)","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HCT","Hct NORMAL ญ","B","F","",36,48,"ความเข้มข้นของเลือดอยู่ในเกณฑ์ปกติ","Complete blood count : Normal","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HCT","Hct H ญ","B","F","",48.01,9999,"ความเข้มข้นของเลือดสูงกว่าเกณฑ์ปกติ","","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HCT","HCT L ช","B","M","",0,38.99,"ความเข้มข้นของเลือดต่ำกว่าเกณฑ์ปกติ","","ควรรับประทาน : อาหารที่มีธาตุเหล็กสูง เช่น ผักใบเขียว อาหารประเภทเครื่องในสัตว์ เช่น  เลือดไก่/หมู ตับ  กินผลไม้ที่มีวิตามินซีสูงพร้อมมื้ออาหาร เพื่อเพิ่มการดูดซึมธาตุเหล็ก (แนะนำหลีกเลี่ยงการดื่มนมพร้อมมื้ออาหาร)","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HCT","HCT Nornal ช","B","M","",39,50,"ความเข้มข้นของเลือดอยู่ในเกณฑ์ปกติ","","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HCT","HCT H ช","B","M","",50.01,9999,"ความเข้มข้นของเลือดสูงกว่าเกณฑ์ปกติ","","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("WBC","WBC HH","B"," ","",15.01,9999,"ปริมาณเม็ดเลือดขาวในเลือดสูงกว่าเกณฑ์ปกติ","CBC : High number of white blood cell because of being infected or inflamation of the body. See a doctor.","ควรปรึกษาแพทย์","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("WBC","WBC L","B","","",0,4.49,"ปริมาณเม็ดเลือดขาวต่ำกว่าเกณฑ์ปกติ","CBC : Low number of white blood cell because of being infection, Hepatitis, Diabetes, Aplastic anemia, or radiation. See a doctor.","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("WBC","WBC NORMAL","B","","",4.5,10,"ปริมาณเม็ดเลือดขาวอยู่ในเกณฑ์ปกติ","Complete blood count : Normal","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("WBC","WBC H","B","","",10.01,15,"ปริมาณเม็ดเลือดขาวสูงกว่าเกณฑ์เล็กน้อย","","หากมีอาการผิดปกติควรปรึกษาแพทย์","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("RBC","RBC L","B"," ","",0,4.2,"จำนวนเม็ดเลือดแดงต่ำกว่าปกติ","- Complete blood count : Low number of red blood cell (Anemia), See a doctor.","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("RBC","RBC NORMAL","B"," ","",4.3,5.5,"จำนวนเม็ดเลือดแดงอยู่ในเกณฑ์ปกติ","- Complete blood count : Normal","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("RBC","RBC H","B","","",5.51,9999,"จำนวนเม็ดเลือดแดงสูงกว่าปกติ","- Complete blood count : High number of Red blood cell (Polycythemia)","แนะนำปรึกษาแพทย์","See a doctor.",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("PLC","Platelet Count L","B","","",0,139.99,"จำนวนเกล็ดเลือดต่ำ","- CBC : Low blood scale (thrombocytopenia). See a doctor for advice.","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("PLC","Platelet Count Normal","B","","",140,400,"จำนวนเกล็ดเลือดอยู่ในเกณฑ์ปกติ","","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("PLC","Platelet Count H","B","","",400.01,9999,"จำนวนเกล็ดเลือดสูง","- CBC : High blood scale (Thrombocytosis). ","ควรปรึกษาแพทย์","See a doctor for advice.",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("FBS","FBS L","B","","",0,73,"น้ำตาลในเลือดต่ำกว่าเกณฑ์ปกติ","","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("FBS","FBS Normal","B","","",74,99,"น้ำตาลในเลือดอยู่ในเกณฑ์ปกติ","- Fasting Blood Sugar : Normal","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("FBS","FBS H","B","","",100,9999,"น้ำตาลในเลือดสูงกว่าเกณฑ์ปกติ","","ควรหลีกเลี่ยง : ข้าวแป้งที่ซ้ำซ้อน เช่น เผือก มัน ฟักทอง ข้าวโพด และจำกัดปริมาณผลไม้ ควรรับประทานผลไม้น้ำตาลต่ำ 1-2 ผลต่อวัน เนื้อสัตว์อย่างน้อย 6-8 ช้อนกินข้าว/มื้อ และผักประเภทใบ 3-6 ทัพพี/วัน","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HBA1C","HBA1C L","B","","",0,4.79,"น้ำตาลสะสมในเลือดต่ำกว่าเกณฑ์ปกติ","","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HBA1C","HBA1C Normal","B","","",4.8,5.9,"น้ำตาลสะสมในเลือดอยู่ในเกณฑ์ปกติ","- Glycosylated (%HbA1c) : Normal","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HBA1C","HbA1C H","B","","",6,9999,"น้ำตาลสะสมในเลือดอยู่สูงกว่าเกณฑ์ปกติ","","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CHOL","CHOL Normal","B","","",0,200,"ไขมันคลอเลสเตอรอลในเลือดอยู่ในเกณฑ์ปกติ","","","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CHOL","CHOL H","B","","",200.01,250,"ไขมันคลอเลสเตอรอลในเลือดสูงกว่าเกณฑ์ปกติเล็กน้อย","","ควรหลีกเลี่ยง : น้ำมันไขมันอิ่มตัวสูง เช่น น้ำมันหมู น้ำมันปาล์ม น้ำมันมะพร้าว และกะทิ หลีกเลี่ยงเนื้อสัตว์ติดมัน แนะนำเนื้อสัตว์ไม่ติดมัน เช่น อกไก่ น้ำมันถั่วเหลือง น้ำมันมะกอก น้ำมันรำข้าว อะโวคาโด","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CHOL","CHOL HHH","B","","",250.01,9999,"ไขมันคลอเลสเตอรอลในเลือดสูงกว่าเกณฑ์ปกติ","Cholesterol : Very high, See a doctor.","ควรหลีกเลี่ยง: น้ำมันไขมันอิ่มตัวสูง เช่น น้ำมันหมู น้ำมันปาล์ม น้ำมันมะพร้าว และกะทิ หลีกเลี่ยงเนื้อสัตว์ติดมัน แนะนำเนื้อสัตว์ไม่ติดมัน เช่น อกไก่ น้ำมันถั่วเหลือง น้ำมันมะกอก น้ำมันรำข้าว อะโวคาโด","",new DateTime(2000,1,1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999,12,31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("TRI", "Triglyceride Normal", "B", "", "", 0, 150, "ไขมันไตรกลีเซอร์ไรด์อยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("TRI", "Triglyceride H", "B", "", "", 150.01, 9999, "ไขมันไตรกลีเซอร์ไรด์สูงกว่าเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HDL", "HDL FL", "B", "F", "", 0, 65, "ไขมันความหนาแน่นสูงต่ำกว่าเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HDL", "HDL FN", "B", "F", "", 65, 9999, "ไขมันความหนาแน่นสูง อยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HDL", "HDL ML", "B", "M", "", 0, 55, "ไขมันความหนาแน่นสูง ต่ำกว่าเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HDL", "HDL MN", "B", "M", "", 55, 9999, "ไขมันความหนาแน่นสูง อยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("LDL", "LDL", "B", "", "", 0, 100, "ไขมันความหนาแน่นต่ำอยู่ในเกณฑ์ปกติ", "- LDL : Normal", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("LDL", "LDL H", "B", "", "", 100.01, 150, "ไขมันความหนาแน่นต่ำสูงกว่าเกณฑ์ปกติเล็กน้อย", "- LDL cholesterol : Slightly high. Prevent high cholestoral diets,exercise regulary and repeat blood test in 4-6 months.", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("LDL", "LDL HHH", "B", "", "", 150, 9999, "ไขมันความหนาแน่นต่ำสูงกว่าเกณฑ์ปกติ", "- LDL cholesterol : Very high, See a doctor.", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("UR", "URIC Normal F", "B", "F", "", 2.4, 5.7, "กรดยูริคในเลือดสูงมาก", "Uric Acid : High uric acid", "ควรหลีกเลี่ยง : สัตว์ปีก ผักตระกูลยอดและเมล็ดผักต่างๆ ถั่วทุกชนิด เช่น ธัญพืชต้ม นมถั่วเหลือง น้ำเต้าหู้ เครื่องในสัตว์ ปลาไม่มีเกล็ด น้ำซุปกระดูก/น้ำซุปก๋วยเตี๋ยว", "See a doctor.", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("UR", "URIC H F", "B", "F", "", 5.71, 9999, "กรดยูริคในเลือดสูงเล็กน้อย", "", "ควรหลีกเลี่ยง : สัตว์ปีก ผักตระกูลยอดและเมล็ดผักต่างๆ ถั่วทุกชนิด เช่น ธัญพืชต้ม นมถั่วเหลือง น้ำเต้าหู้ เครื่องในสัตว์ ปลาไม่มีเกล็ด น้ำซุปกระดูก/น้ำซุปก๋วยเตี๋ยว", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("UR", "URIC Normal M", "B", "M", "", 3.4, 7, "กรดยูริคในเลือดอยู่ในเกณฑ์ปกติ", "Uric Acid : Normal", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("UR", "URIC H M", "B", "M", "", 7.01, 9999, "กรดยูริคในเลือดสูงเล็กน้อย", "", "ควรหลีกเลี่ยง : สัตว์ปีก ผักตระกูลยอดและเมล็ดผักต่างๆ ถั่วทุกชนิด เช่น ธัญพืชต้ม นมถั่วเหลือง น้ำเต้าหู้ เครื่องในสัตว์ ปลาไม่มีเกล็ด น้ำซุปกระดูก/น้ำซุปก๋วยเตี๋ยว", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("BUN", "BUN Normal F", "B", "F", "", 7, 18.7, "การทำงานของไตอยู่ในเกณฑ์ปกติ", "- Kidney function (BUN) : Normal", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("BUN", "BUN H F", "B", "F", "", 18.71, 9999, "การทำงานของไตลดลง ", "- Kidney function (BUN) : Decrease", "แนะนำพบแพทย์", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("BUN", "BUN Normal M", "B", "M", "", 8.9, 20.6, "การทำงานของไตอยู่ในเกณฑ์ปกติ", "- Kidney function (BUN) : Normal", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("BUN", "BUN H M", "B", "M", "", 20.61, 9999, "การทำงานของไตลดลง ", "- Kidney function (BUN) : Decrease", "แนะนำพบแพทย์", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CRE", "Creatinine Female", "B", "F", "", 0.51, 0.95, "การทำงานของไตอยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CRE", "Creatinine Female H", "B", "F", "", 0.96, 9999, "การทำงานของไตต่ำกว่าปกติ", "", "แนะนำพบแพทย์", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CRE", "Creatinine Male", "B", "M", "", 0.67, 1.17, "การทำงานของไตอยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CRE", "Creatinine Male H", "B", "M", "", 1.18, 9999, "การทำงานของไตต่ำกว่าปกติ", "", "แนะนำพบแพทย์", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("AST", "SGOT F Normal", "B", "F", "", 0, 35, "เอนไซม์ SGOT ในตับอยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("AST", "SGOT F H", "B", "F", "", 35.01, 9999, "เอนไซม์ SGOT ในตับสูง ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("AST", "SGOT M Normal", "B", "M", "", 0, 50, "เอนไซม์ SGOT ในตับอยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("AST","SGOT M H","B","M","",50.01,9999,"เอนไซม์ SGOT ในตับสูง ","- SGOT : Extremely high liver enzyme. Liver imflammation.","ควรพบแพทย์ทันที","See a doctor immediately.",new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("ALT", "SGPT F ", "B", "F", "", 0, 35, "เอนไซม์ SGPT ในตับอยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("ALT", "SGPT F H", "B", "F", "", 35.01, 9999, "เอนไซม์ SGPT ในตับสูง ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("ALT", "SGPT M ", "B", "M", "", 0, 50, "เอนไซม์ SGPT ในตับอยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("ALT", "SGPT M H", "B", "M", "", 50.01, 9999, "เอนไซม์ SGPT ในตับสูง ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("ALP", "ALP Normal F", "B", "F", "", 0, 104, "เอนไซม์ ALP ในตับอยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("ALP", "ALP H F", "B", "F", "", 105, 9999, "เอนไซม์ ALP ในตับขึ้นสูง", "", "แนะนำพบแพทย์", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("ALP", "ALP Normal M", "B", "M", "", 0, 129, "เอนไซม์ ALP ในตับอยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("ALP", "ALP H M", "B", "M", "", 130, 9999, "เอนไซม์ ALP ในตับขึ้นสูง", "", "แนะนำพบแพทย์", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("TSH", "TSH L", "B", "", "", 0, 0.27, "ฮอร์โมนไทรอยด์ TSH ต่ำกว่าเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("TSH", "TSH H", "B", "", "", 4.201, 9999, "ฮอร์โมนไทรอยด์ TSH สูงกว่าเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("TSH", "TSH Normal", "B", "", "", 0.271, 4.2, "ฮอร์โมนไทรอยด์ TSH อยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("FT3", "Free T3 L F", "B", "F", "", 0, 1.88, "ฮอร์โมนไทรอยด์ FT3 ต่ำกว่าเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("FT3", "Free T3 Normal F", "B", "F", "", 1.88, 3.18, "ฮอร์โมนไทรอยด์ FT3 อยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("FT3", "Free T3 H F", "B", "F", "", 3.18, 9999, "ฮอร์โมนไทรอยด์ FT3 สูงกว่าเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("FT3", "Free T3 L M", "B", "M", "", 0, 2.77, "ฮอร์โมนไทรอยด์ FT3 ต่ำกว่าเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("FT3", "Free T3 Normal M", "B", "M", "", 2.78, 5.27, "ฮอร์โมนไทรอยด์ FT3 อยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("FT3", "Free T3 H M", "B", "M", "", 5.28, 9999, "ฮอร์โมนไทรอยด์ FT3 สูงกว่าเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("FT4", "FT4 Normal", "B", "", "", 0.92, 1.68, "ฮอร์โมนไทรอยด์ FT4 อยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("FT4", "FT4 H", "B", "", "", 1.69, 9999, "ฮอร์โมนไทรอยด์ FT4 สูงกว่าเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("AFP", "AFP Normal", "B", "", "", 0, 7, "สารบ่งชี้มะเร็งตับอยู่ในเกณฑ์ปกติ", "Normal", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("AFP", "AFP H", "B", "", "", 7.01, 9999, "สารบ่งชี้มะเร็งตับ สูงเกินเกณฑ์ปกติ", "", "แนะนำพบแพทย์", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CA125", "CA125 Normal", "B", "", "", 0, 35, "สารบ่งชี้มะเร็งรังไข่ อยู่ในเกณฑ์ปกติ", "Normal", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CA125", "CA125 H", "B", "", "", 35.01, 9999, "สารบ่งชี้มะเร็งรังไข่ สูงเกินเกณฑ์ปกติ", "High", "แนะนำปรึกษาแพทย์", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CA199", "CA19-9 Normal", "B", "", "", 0, 39, "สารบ่งชี้มะเร็งตับอ่อน อยู่ในเกณฑ์ปกติ", "Normal", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CA199", "CA19-9 H", "B", "", "", 39.01, 9999, "สารบ่งชี้มะเร็งตับอ่อน สูงเกินเกณฑ์ปกติ", "High", "แนะนำปรึกษาแพทย์", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CEA", "CEA Normal F", "B", "F", "", 0, 4.7, "สารบ่งชี้มะเร็งลำไส้อยู่ในเกณฑ์ปกติ", "Normal", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CEA", "CEA H F", "B", "F", "", 4.8, 9999, "สารบ่งชี้มะเร็งลำไส้ สูงเกินเกณฑ์ปกติ", "High", "แนะนำปรึกษาแพทย์", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CEA", "CEA Normal M", "B", "M", "", 0, 5, "สารบ่งชี้มะเร็งลำไส้อยู่ในเกณฑ์ปกติ", "Normal", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("CEA", "CEA H M", "B", "M", "", 5.01, 9999, "สารบ่งชี้มะเร็งลำไส้ สูงเกินเกณฑ์ปกติ", "High", "แนะนำปรึกษาแพทย์", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("PSA", "PSA Normal", "B", "", "", 0, 4, "สารบ่งชี้มะเร็งต่อมลูกหมากอยู่ในเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("PSA", "PSA H", "B", "", "", 4.01, 9999, "สารบ่งชี้มะเร็งต่อมลูกหมาก สูงเกินเกณฑ์ปกติ", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HBAgI", "Hepatitis B surface Antigen (Quantitative)", "E", "", "Non reactive", 0, 0, "ปกติ, ไม่พบเชื้อไวรัสตับอักเสบบี", "- HBsAg : Normal, No found HVB.", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HBAgI", "Hepatitis B surface Antigen (Quantitative)", "E", "", "Negative", 0, 0, "ปกติ, ไม่พบเชื้อไวรัสตับอักเสบบี", "- HBsAg : Normal, No found HVB.", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HBAgI", "Hepatitis B surface Antigen (Quantitative)", "E", "", "Positive", 0, 0, "พบเชื้อไวรัสตับอักเสบบี", "HBsAg Found", "แนะนำปรึกษาแพทย์", "Consult a doctor.", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HBAgI", "Hepatitis B surface Antigen (Quantitative)", "E", "", "Reactive", 0, 0, "พบเชื้อไวรัสตับอักเสบบี", "HBsAg Found", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HBAnI", "Anti HBs N", "E", "", "Negative", 0, 0, "ไม่มีภูมิคุ้มกันไวรัสตับอักเสบบี", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HBAnI", "Anti HBs non", "E", "", "Non reactive", 0, 0, "ไม่มีภูมิคุ้มกันไวรัสตับอักเสบบี", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HBAnI", "Anti HBs P", "E", "", "Positive", 0, 0, "มีภูมิคุ้มกันไวรัสตับอักเสบบี", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
            new Recommendation("HBAnI", "Anti HBs Re", "E", "", "Reactive", 0, 0, "มีภูมิคุ้มกันไวรัสตับอักเสบบี", "", "", "", new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(2999, 12, 31, 0, 0, 0, DateTimeKind.Utc)),
        };

        await _context.Recommendations.AddRangeAsync(Recommendation, cancellationToken);
        await _context.SaveChangesAsync(cancellationToken);
    }
     
}
